# Generated by Django 5.1.2 on 2024-11-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
